"""The unit of work: every repository in one transaction.

Services never open their own transactions; the API layer enters the
unit, services run against it, and a single commit makes multi-write
operations (organization + membership + audit + outbox, invitation
consume + membership) atomic by construction.
"""

from typing import Protocol
from uuid import UUID

from modules.platform.domain.entities import (
    AppUser,
    AuditEntry,
    Invitation,
    Membership,
    Organization,
    OutboxEvent,
    Project,
    ProjectMembership,
    ProjectTag,
    Team,
    TeamMembership,
)


class AppUsers(Protocol):
    async def get_by_id(self, app_user_id: UUID) -> AppUser | None: ...
    async def get_id_by_email(self, email: str) -> UUID | None: ...


class Organizations(Protocol):
    async def create(self, organization: Organization) -> None: ...
    async def get(self, organization_id: UUID) -> Organization | None: ...
    async def update(self, organization: Organization) -> None: ...
    async def delete(self, organization_id: UUID) -> None: ...
    async def list_for_user(self, app_user_id: UUID) -> list[Organization]: ...


class Memberships(Protocol):
    async def get(
        self, organization_id: UUID, app_user_id: UUID
    ) -> Membership | None: ...
    async def list(self, organization_id: UUID) -> list[Membership]: ...
    async def add(self, membership: Membership) -> None: ...
    async def update_role(
        self, organization_id: UUID, app_user_id: UUID, role: str
    ) -> None: ...
    async def remove(self, organization_id: UUID, app_user_id: UUID) -> None: ...
    async def count_role(self, organization_id: UUID, role: str) -> int: ...


class Teams(Protocol):
    async def create(self, team: Team) -> None: ...
    async def get(self, team_id: UUID) -> Team | None: ...
    async def update(self, team: Team) -> None: ...
    async def delete(self, team_id: UUID) -> None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[Team]: ...


class TeamMemberships(Protocol):
    async def get(self, team_id: UUID, app_user_id: UUID) -> TeamMembership | None: ...
    async def list(self, team_id: UUID) -> list[TeamMembership]: ...
    async def add(self, membership: TeamMembership) -> None: ...
    async def remove(self, team_id: UUID, app_user_id: UUID) -> None: ...


class Projects(Protocol):
    async def create(self, project: Project) -> None: ...
    async def get(self, project_id: UUID) -> Project | None: ...
    async def update(self, project: Project) -> None: ...
    async def delete(self, project_id: UUID) -> None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[Project]: ...


class ProjectMemberships(Protocol):
    async def get(
        self, project_id: UUID, app_user_id: UUID
    ) -> ProjectMembership | None: ...
    async def list(self, project_id: UUID) -> list[ProjectMembership]: ...
    async def add(self, membership: ProjectMembership) -> None: ...
    async def remove(self, project_id: UUID, app_user_id: UUID) -> None: ...


class Tags(Protocol):
    """Project tag repository — every query applies the explicit tenant
    scope (organization_id + project_id) (ticket #8 acceptance)."""

    async def create(self, tag: ProjectTag) -> None: ...
    async def get(
        self, organization_id: UUID, project_id: UUID, tag_id: UUID
    ) -> ProjectTag | None: ...
    async def update(self, tag: ProjectTag) -> None: ...
    async def delete(
        self, organization_id: UUID, project_id: UUID, tag_id: UUID
    ) -> None: ...
    async def list_for_project(
        self, organization_id: UUID, project_id: UUID
    ) -> list[ProjectTag]: ...


class Invitations(Protocol):
    async def create(self, invitation: Invitation) -> None: ...
    async def get_by_token_hash(self, token_hash: str) -> Invitation | None: ...
    async def consume(self, invitation_id: UUID) -> bool:
        """Atomic single-use claim. Returns True exactly once per
        invitation; concurrent racers lose the race."""
        ...


class AuditLog(Protocol):
    async def record(self, entry: AuditEntry) -> None: ...


class Outbox(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...


class PlatformUnit(Protocol):
    """One transaction worth of repositories."""

    app_users: AppUsers
    organizations: Organizations
    memberships: Memberships
    teams: Teams
    team_memberships: TeamMemberships
    projects: Projects
    project_memberships: ProjectMemberships
    tags: Tags
    invitations: Invitations
    audit: AuditLog
    outbox: Outbox

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
